server:
  port: 8083
hm:
  jwt:
    location: classpath:hmall.jks
    alias: hmall
    password: hmall123
    tokenTTL: 30m
  db:
    database: hm-user
  swagger:
    title: 黑马商城用户管理接口文档
    description: "黑马商城用户管理接口文档"
    package: com.hmall.user.controller
feign:
  okhttp:
    enabled: true
  sentinel:
    enabled: true